arm_with_torso:

  reference_frame: "world"
  gimbal_scale: 0.2
  num_robot_placements: 10 

  reference_names: 
    - human
  
  reference_data:
    human: 
      mesh: "package://task_ui/meshes/person_standing_1_75_height_reference.dae"
      pose: [1.5, 0.5, 1.1, 0, 0.0, 0.0]

###################################################
  object_names:
    - mug
    
  object_data:
    mug:
      mesh: "package://task_ui/meshes/cup_1.dae"
      grasp_offset: [0.0, -0.08, 0.10, -1.5708, 0.0, 0.0]    

####################################################

  step_names:
    - step_0
  
  step_data:    
    step_0:
      object: mug
      pose: [0.3, 0.0, 0.0, 0, 0.0, 0.0]
      reference: human  


